# **ONLINE RETAIL(Cleaning Process)**

In [1]:
from google.colab import files

uploaded = files.upload()

Saving online_retail_II.csv to online_retail_II.csv

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("online_retail_II.csv")
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [4]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [5]:
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [6]:
df.shape

(1067371, 8)

In [7]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [9]:
df['Invoice'].str.contains('[A-Za-z]').sum() #understanding why invoice is in object because there are some cancelled orders like C489449

np.int64(19500)

In [10]:
df[df['Invoice'].str.startswith('C')]['Quantity'].describe() #describing all cancelled invoice

count    19494.000000
mean       -25.186827
std        805.104908
min     -80995.000000
25%         -6.000000
50%         -2.000000
75%         -1.000000
max          1.000000
Name: Quantity, dtype: float64

In [11]:
df[(df['Invoice'].str.startswith('C')) & (df['Quantity'] > 0)] #found a HUGE negative quantity: -80,995
df[df['Quantity'] == -80995]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1065883,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2011-12-09 09:27:00,2.08,16446.0,United Kingdom

In [12]:
df.duplicated().sum()

np.int64(34335)

In [13]:
df[df.duplicated()].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom

In [14]:
df = df.drop_duplicates() #Dropped duplicates

In [15]:
df.shape

(1033036, 8)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1033036 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1033036 non-null  object
 1   StockCode    1033036 non-null  object
 2   Description  1028761 non-null  object
 3   Quantity     1033036 non-null  int64
 4   InvoiceDate  1033036 non-null  object
 5   Price        1033036 non-null  float64
 6   Customer ID  797885 non-null   float64
 7   Country      1033036 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 70.9+ MB

In [17]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate']) #Converted invoicedate to Datetime

/tmp/ipykernel_4696/2477866267.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate']) #Converted invoicedate to Datetime

In [18]:
df.info() #Checking whether invoicedate is changed

<class 'pandas.core.frame.DataFrame'>
Index: 1033036 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1033036 non-null  object
 1   StockCode    1033036 non-null  object
 2   Description  1028761 non-null  object
 3   Quantity     1033036 non-null  int64
 4   InvoiceDate  1033036 non-null  datetime64[ns]
 5   Price        1033036 non-null  float64
 6   Customer ID  797885 non-null   float64
 7   Country      1033036 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 70.9+ MB

In [19]:
df['Customer ID'] = df['Customer ID'].astype('Int64') #Converted customer_id from object to int

/tmp/ipykernel_4696/3591849433.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Customer ID'] = df['Customer ID'].astype('Int64') #Converted customer_id from object to int

In [20]:
df.info() #Checking all the datatypes are in correct format

<class 'pandas.core.frame.DataFrame'>
Index: 1033036 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1033036 non-null  object
 1   StockCode    1033036 non-null  object
 2   Description  1028761 non-null  object
 3   Quantity     1033036 non-null  int64
 4   InvoiceDate  1033036 non-null  datetime64[ns]
 5   Price        1033036 non-null  float64
 6   Customer ID  797885 non-null   Int64
 7   Country      1033036 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 71.9+ MB

In [21]:
df[df['Quantity'] == '-80995'] #Researching about quantity that has -80995 and checking whether this a type error
df[df['Quantity'] == '80995']

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [22]:
df[df['Quantity'] == '80995']

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [23]:
df['Quantity'].describe()  #quantity describe

count    1.033036e+06
mean     1.007688e+01
std      1.751976e+02
min     -8.099500e+04
25%      1.000000e+00
50%      3.000000e+00
75%      1.000000e+01
max      8.099500e+04
Name: Quantity, dtype: float64

In [24]:
df[df['Quantity'].abs() == '80995' ]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [25]:
df.sort_values('Quantity').head()#Found the quantity -80995

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1065883,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2011-12-09 09:27:00,2.08,16446,United Kingdom
587085,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,2011-01-18 10:17:00,1.04,12346,United Kingdom
750991,556691,23005,printing smudges/thrown away,-9600,2011-06-14 10:37:00,0.00,<NA>,United Kingdom
303996,519017,22759,NaN,-9600,2010-08-13 09:14:00,0.00,<NA>,United Kingdom
750990,556690,23005,printing smudges/thrown away,-9600,2011-06-14 10:37:00,0.00,<NA>,United Kingdom

In [26]:
df.sort_values('Quantity').tail() #and found the quantity 80995	understood the order is been cancelled

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
127168,501534,21091,SET/6 WOODLAND PAPER PLATES,12960,2010-03-17 13:09:00,0.10,13902,Denmark
127166,501534,21099,SET/6 STRAWBERRY PAPER CUPS,12960,2010-03-17 13:09:00,0.10,13902,Denmark
90857,497946,37410,BLACK AND WHITE PAISLEY FLOWER MUG,19152,2010-02-15 11:57:00,0.10,13902,Denmark
587080,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346,United Kingdom
1065882,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446,United Kingdom

In [27]:
df['cancelled'] = df['Invoice'].str.startswith('C') #Stored Cancelled orders in a column

/tmp/ipykernel_4696/3734688284.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cancelled'] = df['Invoice'].str.startswith('C') #Stored Cancelled orders in a column

In [28]:
df.isna().sum()

Invoice             0
StockCode           0
Description      4275
Quantity            0
InvoiceDate         0
Price               0
Customer ID    235151
Country             0
cancelled           0
dtype: int64

In [29]:
df['Price'].eq(0).sum() #Checking price that is equal to 0

np.int64(6014)

In [30]:
df[df['Price'] < 0].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,<NA>,United Kingdom,False
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,<NA>,United Kingdom,False
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,<NA>,United Kingdom,False
825444,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,<NA>,United Kingdom,False
825445,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,<NA>,United Kingdom,False

In [33]:

df[df['Price'] == 0].head(10) #checking price value that has 0

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,<NA>,United Kingdom,False
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,<NA>,United Kingdom,False
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,<NA>,United Kingdom,False
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,<NA>,United Kingdom,False
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,<NA>,United Kingdom,False
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,<NA>,United Kingdom,False
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0,<NA>,United Kingdom,False
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0,<NA>,United Kingdom,False
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,<NA>,United Kingdom,False
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,<NA>,United Kingdom,False

In [34]:
zero_price = df[df['Price'] == 0]
df = df[df['Price'] != 0] #Keeps only the row where the price is not 0

In [35]:
df.shape

(1027022, 9)

In [36]:
df['Description'].isna().sum()#Checking description null values becomes 0 after deleting price that has 0 values.
                              #Most of the description has the price value 0

np.int64(0)

In [37]:
df.isna().sum()

Invoice             0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
Price               0
Customer ID    229207
Country             0
cancelled           0
dtype: int64

In [38]:
df['Description'] = df['Description'].str.strip()#This removes extra spaces in description

In [39]:
df.head(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,False
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,False
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,False
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,False
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,False

In [40]:
df['Description'].nunique() #nunique() counts how many different values a column has, ignoring repeats.

5373

In [41]:
Not_Products = df[df['StockCode'].str.contains('[0-9]') == False] #Investigating stockcode that aren't products

In [42]:
Not_Products['StockCode'].value_counts() #Not a Product List

StockCode
POST            2079
DOT             1418
M               1380
D                173
S                101
BANK CHARGES     100
ADJUST            67
AMAZONFEE         36
DCGSSGIRL         23
DCGSSBOY          21
PADS              18
CRUK              16
B                  6
m                  5
Name: count, dtype: int64

**NON PRODUCTS**

In [43]:
df[df['StockCode'] == 'BANK CHARGES'].head(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
18410,C490943,BANK CHARGES,Bank Charges,-1,2009-12-08 14:08:00,15.00,16703,United Kingdom,True
18466,490948,BANK CHARGES,Bank Charges,1,2009-12-08 14:29:00,15.00,16805,United Kingdom,False
33435,C492206,BANK CHARGES,Bank Charges,-1,2009-12-15 16:32:00,848.43,<NA>,United Kingdom,True
55948,C494438,BANK CHARGES,Bank Charges,-1,2010-01-14 12:15:00,767.99,<NA>,United Kingdom,True
94431,498269,BANK CHARGES,Bank Charges,1,2010-02-17 15:03:00,15.00,16928,United Kingdom,False

In [44]:
df[df['StockCode'] == 'POST'].head(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
89,489439,POST,POSTAGE,3,2009-12-01 09:28:00,18.00,12682,France,False
126,489444,POST,POSTAGE,1,2009-12-01 09:55:00,141.00,12636,USA,False
173,489447,POST,POSTAGE,1,2009-12-01 10:10:00,130.00,12362,Belgium,False
625,489526,POST,POSTAGE,6,2009-12-01 11:50:00,18.00,12533,Germany,False
927,C489538,POST,POSTAGE,-1,2009-12-01 12:18:00,9.58,15796,United Kingdom,True

In [45]:
df[df['StockCode'] == 'DOT'].head(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
2379,489597,DOT,DOTCOM POSTAGE,1,2009-12-01 14:28:00,647.19,<NA>,United Kingdom,False
2539,489600,DOT,DOTCOM POSTAGE,1,2009-12-01 14:43:00,55.96,<NA>,United Kingdom,False
2551,489601,DOT,DOTCOM POSTAGE,1,2009-12-01 14:44:00,68.39,<NA>,United Kingdom,False
2571,489602,DOT,DOTCOM POSTAGE,1,2009-12-01 14:45:00,59.35,<NA>,United Kingdom,False
2619,489603,DOT,DOTCOM POSTAGE,1,2009-12-01 14:46:00,42.39,<NA>,United Kingdom,False

In [46]:
df[df['StockCode'] == 'M'].head(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
2697,489609,M,Manual,1,2009-12-01 14:50:00,4.00,<NA>,United Kingdom,False
3053,C489651,M,Manual,-1,2009-12-01 16:48:00,5.10,17804,United Kingdom,True
5897,C489859,M,Manual,-1,2009-12-02 14:45:00,69.57,<NA>,United Kingdom,True
9259,C490126,M,Manual,-1,2009-12-03 18:12:00,5.95,15884,United Kingdom,True
9307,C490129,M,Manual,-1,2009-12-03 18:26:00,1998.49,15482,United Kingdom,True

In [47]:
df[df['StockCode'] == 'D'].head(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
735,C489535,D,Discount,-1,2009-12-01 12:11:00,9.00,15299,United Kingdom,True
736,C489535,D,Discount,-1,2009-12-01 12:11:00,19.00,15299,United Kingdom,True
24675,C491428,D,Discount,-1,2009-12-10 20:23:00,9.10,15494,United Kingdom,True
29414,C491845,D,Discount,-1,2009-12-14 14:54:00,1.59,<NA>,United Kingdom,True
29958,C491962,D,Discount,-1,2009-12-14 16:38:00,0.59,13206,United Kingdom,True

In [48]:
df[df['StockCode'] == 'S'].head(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
114061,C500305,S,SAMPLES,-1,2010-03-07 10:59:00,73.80,<NA>,United Kingdom,True
114083,C500309,S,SAMPLES,-1,2010-03-07 11:09:00,32.03,<NA>,United Kingdom,True
133558,C502083,S,SAMPLES,-1,2010-03-22 15:50:00,170.37,<NA>,United Kingdom,True
133582,C502088,S,SAMPLES,-1,2010-03-22 16:03:00,259.59,<NA>,United Kingdom,True
136253,C502438,S,SAMPLES,-1,2010-03-24 13:11:00,605.18,<NA>,United Kingdom,True

In [49]:
df[df['StockCode'] == 'CRUK'].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
842969,C564763,CRUK,CRUK Commission,-1,2011-08-30 10:49:00,1.60,14096,United Kingdom,True
849464,C565382,CRUK,CRUK Commission,-1,2011-09-02 15:45:00,13.01,14096,United Kingdom,True
859206,C566216,CRUK,CRUK Commission,-1,2011-09-09 15:17:00,15.96,14096,United Kingdom,True
864273,C566565,CRUK,CRUK Commission,-1,2011-09-13 12:32:00,52.24,14096,United Kingdom,True
876043,C567655,CRUK,CRUK Commission,-1,2011-09-21 14:40:00,608.66,14096,United Kingdom,True
887050,C568345,CRUK,CRUK Commission,-1,2011-09-26 15:28:00,447.56,14096,United Kingdom,True
898246,C569245,CRUK,CRUK Commission,-1,2011-10-03 09:57:00,361.59,14096,United Kingdom,True
915425,C570487,CRUK,CRUK Commission,-1,2011-10-10 17:12:00,411.92,14096,United Kingdom,True
927228,C571440,CRUK,CRUK Commission,-1,2011-10-17 13:31:00,495.98,14096,United Kingdom,True
941573,C572551,CRUK,CRUK Commission,-1,2011-10-24 17:07:00,425.14,14096,United Kingdom,True

In [50]:
df[df['StockCode'] == 'B'].head(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,<NA>,United Kingdom,False
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,<NA>,United Kingdom,False
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,<NA>,United Kingdom,False
825443,A563185,B,Adjust bad debt,1,2011-08-12 14:50:00,11062.06,<NA>,United Kingdom,False
825444,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,<NA>,United Kingdom,False

In [51]:
df[df['StockCode'] == 'm']

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
96608,498492,m,Manual,1,2010-02-19 10:56:00,2.55,<NA>,United Kingdom,False
96609,498492,m,Manual,1,2010-02-19 10:56:00,3.40,<NA>,United Kingdom,False
157226,504396,m,Manual,1,2010-04-13 11:45:00,4.00,<NA>,United Kingdom,False
228780,511509,m,Manual,1,2010-06-08 15:26:00,2.55,<NA>,United Kingdom,False
565844,539736,m,Manual,1,2010-12-21 15:18:00,2.55,<NA>,United Kingdom,False

In [52]:
df[df['StockCode'] == 'AMAZONFEE'].head(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
440688,C531400,AMAZONFEE,AMAZON FEE,-1,2010-11-08 10:08:00,6706.71,<NA>,United Kingdom,True
440698,531411,AMAZONFEE,AMAZON FEE,1,2010-11-08 10:11:00,6706.71,<NA>,United Kingdom,False
517452,C537600,AMAZONFEE,AMAZON FEE,-1,2010-12-07 12:41:00,1.00,<NA>,United Kingdom,True
517953,C537630,AMAZONFEE,AMAZON FEE,-1,2010-12-07 15:04:00,13541.33,<NA>,United Kingdom,True
517955,537632,AMAZONFEE,AMAZON FEE,1,2010-12-07 15:08:00,13541.33,<NA>,United Kingdom,False

In [53]:
df[df['StockCode'] == 'ADJUST'].head(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
70975,495732,ADJUST,Adjustment by john on 26/01/2010 16,1,2010-01-26 16:20:00,96.46,<NA>,EIRE,False
70976,495733,ADJUST,Adjustment by john on 26/01/2010 16,1,2010-01-26 16:21:00,68.34,14911,EIRE,False
70977,495735,ADJUST,Adjustment by john on 26/01/2010 16,1,2010-01-26 16:22:00,201.56,12745,EIRE,False
70978,495734,ADJUST,Adjustment by john on 26/01/2010 16,1,2010-01-26 16:22:00,205.82,14911,EIRE,False
70979,C495737,ADJUST,Adjustment by john on 26/01/2010 16,-1,2010-01-26 16:23:00,10.50,16154,United Kingdom,True

**REAL PRODUCTS**

In [54]:
df[df['StockCode'] == 'DCGSSGIRL'].head(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
244831,513099,DCGSSGIRL,GIRLS PARTY BAG,3,2010-06-21 15:13:00,3.36,<NA>,United Kingdom,False
246184,513200,DCGSSGIRL,GIRLS PARTY BAG,6,2010-06-22 16:28:00,3.36,<NA>,United Kingdom,False
249938,513574,DCGSSGIRL,GIRLS PARTY BAG,1,2010-06-25 15:13:00,3.36,<NA>,United Kingdom,False
251930,513655,DCGSSGIRL,GIRLS PARTY BAG,5,2010-06-28 10:02:00,3.36,<NA>,United Kingdom,False
253997,513907,DCGSSGIRL,GIRLS PARTY BAG,1,2010-06-29 12:08:00,3.36,<NA>,United Kingdom,False

In [55]:
df[df['StockCode'] == 'PADS'].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
62299,494914,PADS,PADS TO MATCH ALL CUSHIONS,1,2010-01-19 17:04:00,0.001,16705,United Kingdom,False
74731,496222,PADS,PADS TO MATCH ALL CUSHIONS,1,2010-01-29 13:53:00,0.001,13583,United Kingdom,False
77702,496473,PADS,PADS TO MATCH ALL CUSHIONS,1,2010-02-01 15:38:00,0.001,17350,United Kingdom,False
79794,496643,PADS,PADS TO MATCH ALL CUSHIONS,1,2010-02-03 11:58:00,0.001,13408,United Kingdom,False
90798,497935,PADS,PADS TO MATCH ALL CUSHIONS,1,2010-02-15 10:47:00,0.001,13408,United Kingdom,False
97716,498562,PADS,PADS TO MATCH ALL CUSHIONS,1,2010-02-21 12:03:00,0.001,15182,United Kingdom,False
101718,499056,PADS,PADS TO MATCH ALL CUSHIONS,1,2010-02-24 13:46:00,0.001,13765,United Kingdom,False
104480,499399,PADS,PADS TO MATCH ALL CUSHIONS,1,2010-02-26 13:26:00,0.001,14459,United Kingdom,False
123947,501176,PADS,PADS TO MATCH ALL CUSHIONS,1,2010-03-15 11:00:00,0.001,14857,United Kingdom,False
156809,504332,PADS,PADS TO MATCH ALL CUSHIONS,1,2010-04-12 16:30:00,0.001,12671,Germany,False

In [56]:
df[df['StockCode'] == 'DCGSSBOY'].head(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,cancelled
244830,513099,DCGSSBOY,BOYS PARTY BAG,5,2010-06-21 15:13:00,3.36,<NA>,United Kingdom,False
246183,513200,DCGSSBOY,BOYS PARTY BAG,7,2010-06-22 16:28:00,3.36,<NA>,United Kingdom,False
249937,513574,DCGSSBOY,BOYS PARTY BAG,3,2010-06-25 15:13:00,3.36,<NA>,United Kingdom,False
251929,513655,DCGSSBOY,BOYS PARTY BAG,4,2010-06-28 10:02:00,3.36,<NA>,United Kingdom,False
278355,516470,DCGSSBOY,BOYS PARTY BAG,1,2010-07-20 15:28:00,3.36,<NA>,United Kingdom,False

In [57]:
df['StockCode'] = df['StockCode'].str.upper() #changing the stockcode to uppercase

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1027022 entries, 0 to 1067370
Data columns (total 9 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1027022 non-null  object
 1   StockCode    1027022 non-null  object
 2   Description  1027022 non-null  object
 3   Quantity     1027022 non-null  int64
 4   InvoiceDate  1027022 non-null  datetime64[ns]
 5   Price        1027022 non-null  float64
 6   Customer ID  797815 non-null   Int64
 7   Country      1027022 non-null  object
 8   cancelled    1027022 non-null  bool
dtypes: Int64(1), bool(1), datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 72.5+ MB

In [59]:
non_products_list = ['POST', 'DOT', 'M', 'D', 'S', 'BANK CHARGES', 'ADJUST', 'AMAZONFEE', 'CRUK', 'B'] #make a list to store non products list

In [60]:
df.isna().sum()

Invoice             0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
Price               0
Customer ID    229207
Country             0
cancelled           0
dtype: int64

In [61]:
df['Customer ID'].isna().sum()

np.int64(229207)

In [63]:
df.to_csv("cleaned_online_retail II.csv", index= False)

files.download("cleaned_online_retail II.csv")